# Generated by Django 4.1.1 on 2022-09-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
        migrations.RemoveField(
            model_name='income',
            name='cat',
        ),
    ]
