# Generated by Django 4.1.1 on 2022-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_category_options_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='cat',
            field=models.CharField(choices=[('EF', 'Eврофарма'), ('CF', 'Центр софт'), ('DO', 'Доп доходы')], default=None, max_length=255),
        ),
    ]
